export const productos = [
    { name: 'Aloe Vera', price: '$10', image: 'Aloe-Vera.jpg',texto: 'Aloe Vera es una planta suculenta que se ha utilizado durante siglos con fines medicinales. Es conocida por sus propiedades curativas y se utiliza en productos de belleza y cuidado de la piel.' },
    { name: 'Snake Plant', price: '$15', image: 'snake-plant.jpg',texto: 'Snake Plant es una planta de interior popular que es fácil de cuidar y puede sobrevivir en condiciones de poca luz. También es conocida por sus propiedades purificadoras de aire.' },
    { name: 'Peace Lily', price: '$12', image: 'peace-lily.jpg',texto: 'Peace Lily es una planta de interior popular que es conocida por sus flores blancas y su capacidad para purificar el aire. Es fácil de cuidar y puede sobrevivir en condiciones de poca luz.' },
    { name: 'Cactus', price: '$8', image: 'cactus.jpg',texto: 'Cactus es una planta suculenta que es fácil de cuidar y puede sobrevivir en condiciones de poca agua. Es conocida por sus formas únicas y su capacidad para almacenar agua en sus hojas.' },
    { name: 'Fiddle Leaf Fig', price: '$25', image: 'fiddle-leaf-fig.jfif',texto: 'Fiddle Leaf Fig es una planta de interior popular que es conocida por sus hojas grandes y brillantes. Es fácil de cuidar y puede sobrevivir en condiciones de poca luz.' },
    { name: 'Pothos', price: '$7', image: 'pothos.jfif' ,texto: 'Pothos es una planta de interior popular que es fácil de cuidar y puede sobrevivir en condiciones de poca luz. También es conocida por su capacidad para purificar el aire.' },
    { name: 'Spider Plant', price: '$9', image: 'spider-plant.jfif',texto: 'Spider Plant es una planta de interior popular que es fácil de cuidar y puede sobrevivir en condiciones de poca luz. También es conocida por sus propiedades purificadoras de aire.' },
    { name: 'ZZ Plant', price: '$20', image: 'zz-plant.jfif',texto: 'ZZ Plant es una planta de interior popular que es fácil de cuidar y puede sobrevivir en condiciones de poca luz. También es conocida por su capacidad para purificar el aire.' },
    { name: 'Bamboo Palm', price: '$15', image: 'bamboo-palm.jfif',texto: 'Bamboo Palm es una planta de interior popular que es fácil de cuidar y puede sobrevivir en condiciones de poca luz. También es conocida por su capacidad para purificar el aire.' },
    { name: 'Rubber Plant', price: '$18', image: 'rubber-plant.jfif',texto: 'Rubber Plant es una planta de interior popular que es fácil de cuidar y puede sobrevivir en condiciones de poca luz. También es conocida por su capacidad para purificar el aire.' },
    { name: 'Monstera', price: '$22', image: 'monstera.jfif',texto: 'Monstera es una planta de interior popular que es fácil de cuidar y puede sobrevivir en condiciones de poca luz. También es conocida por sus hojas grandes y brillantes.' },
    { name: 'Succulent Mix', price: '$30', image: 'succulent-mix.jfif',texto: 'Succulent Mix es una colección de plantas suculentas que son fáciles de cuidar y pueden sobrevivir en condiciones de poca agua. Son conocidas por sus formas únicas .'}
];
